id: P000257
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །དབུ་མ་ཡང་དག་པར་བརྗོད་པ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  layers:
  - book_title
  - author
  id: KS-PK-06
web_metadata:
  title:
    en: A Perfect Presentation of the Middle Way
    bo: དབུ་མ་ཡང་དག་པར་བརྗོད་པ་ཞེས་བྱ་བ་བཞུགས་སོ། །
  collection:
    en: Pema Karpo Series–  Book 6
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༦
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-06
  category:
    en: Madhyamika
    bo: དབུ་མ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-06.epub
  description:
    en: ''
    bo: ''
